<a href="https://colab.research.google.com/github/Saize1/CRUD/blob/master/MohammadSaizeAli_231030037.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 Creating a row vector and a column vector using user input

In [ ]:
import numpy as np
#Creating a row vector using user input
row_input = input("Enter space-separated values for the row vector: ") #Prompts the user to enter values seperated by spaces and stores
row_values = [float(x) for x in row_input.split()] #typecasting string values from user to float data type and splitting it to store in
row_vect = np.array(row_values) #creates an array of values
print("Row vector:")
print(row_vect) #to print row vector
# Creating a column vector using user input
col_input = input("Enter space-separated values for the column vector: ") #Prompts the user to enter values seperated by spaces and stor
col_values = [float(x) for x in col_input.split()] #typecasting string values from user to float data type and splitting it to store in
col_vect = np.array(col_values).reshape(-1, 1) #reshape(-1,1) is used to change the shape of the array and thereby indicating that the a
print("Column vector:")
print(col_vect) #to print column vector
Enter space-separated values for the row vector: 1 2 3 4 5
Row vector:
[1. 2. 3. 4. 5.]
Enter space-separated values for the column vector: 1 2 3 4 5
Column vector:
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
#Creating a row vector and a column vector manually
import numpy as np
# Creating a row vector manually
row_vect = np.array([1, 2, 3, 4, 5]) #The elements of the array are predefined
print("Row vector:")
print(row_vect)
# Creating a column vector manually
col_vect = np.array([[10], [20], [30], [40], [50]])
print("Column vector:")
print(col_vect)
Row vector:
[1 2 3 4 5]
Column vector:
[[10]
 [20]
 [30]
 [40]
 [50]]

#2 Creating a matrix (5 × 5) using the input method as well as manually and saving it as “a”.


In [ ]:
import numpy as np
# Creating a 5x5 matrix using user input
input_matrix = []
print("Enter values for the 5x5 matrix:")
for _ in range(5):
row_input = input(f"Enter 5 space-separated values for row {_ + 1}: ")
row_values = [float(x) for x in row_input.split()]
input_matrix.append(row_values) #append() is used to add values at the end
a = np.array(input_matrix)
print("Matrix 'a' created using user input:")
print(a)
Enter values for the 5x5 matrix:
Enter 5 space-separated values for row 1: 1 1 1 2 2
Enter 5 space-separated values for row 2: 2 3 3 3 4
Enter 5 space-separated values for row 3: 4 4 5 5 5
Enter 5 space-separated values for row 4: 6 6 6 7 7
Enter 5 space-separated values for row 5: 7 8 8 8 9
Matrix 'a' created using user input:
[[1. 1. 1. 2. 2.]
  [2. 3. 3. 3. 4.]
 [4. 4. 5. 5. 5.]
 [6. 6. 6. 7. 7.]
 [7. 8. 8. 8. 9.]]
# Creating a 5x5 matrix manually
manual_matrix = np.array([
[1, 2, 3, 4, 5],
[5, 4, 3, 2, 1],
[6, 7, 8, 9, 10],
[10, 9, 8, 7, 6],
[11, 12, 13, 14, 15]
])
a = manual_matrix
print("Matrix 'a' created manually:")
print(a)
Matrix 'a' created manually:
[[ 1 2 3 4 5]
 [ 5 4 3 2 1]
 [ 6 7 8 9 10]
 [10 9 8 7 6]
 [11 12 13 14 15]]

#3 Getting the 3rd row

In [ ]:
third_row = a[2, :] #[2,:] the first element in the square brackets indicate row number which starts with 0 and the second the column nu
print("3rd row of the matrix:")
print(third_row)
3rd row of the matrix:
[ 6 7 8 9 10]


#4 Getting the 4th column

In [ ]:
fourth_col = a[:,3]
print("4th column of the matrix:")
print(fourth_col)
4th column of the matrix:
[ 4 2 9 7 14]


#5 Sorting the matrix row-wise and column-wise

In [ ]:
import numpy as np
#Sorting the matrix row-wise
sorted_rows = np.sort(a, axis=1) #this function is used to sort the elements of matrix and axis 1 indicates row
print("Matrix with sorted rows:")
print(sorted_rows)
# Sorting the matrix column-wise
sorted_cols = np.sort(a, axis=0) #axis 0 indicates column here
print("Matrix with sorted columns:")
print(sorted_cols)
Matrix with sorted rows:
[[ 1 2 3 4 5]
 [ 1 2 3 4 5]
 [ 6 7 8 9 10]
 [ 6 7 8 9 10]
 [11 12 13 14 15]]
Matrix with sorted columns:
[[ 1 2 3 2 1]
 [ 5 4 3 4 5]
 [ 6 7 8 7 6]
 [10 9 8 9 10]
 [11 12 13 14 15]]

#6 Applying for loop in matrix, if element is greater than 2, multiplying the element by 10 saving it as “b”

In [ ]:
b = np.copy(a) # Taking a copy of the matrix
for i in range(b.shape[0]):
for j in range(b.shape[1]): #nested for loop is used
if b[i, j] > 2:
b[i, j] *= 10
print("Matrix 'b' after applying for loop:")
print(b)
Matrix 'b' after applying for loop:
[[ 1 2 30 40 50]
 [ 50 40 30 2 1]
 [ 60 70 80 90 100]
 [100 90 80 70 60]
 [110 120 130 140 150]]


#7 Adding matrices 'a' and 'b'

In [ ]:
sum_matrix = a + b
print("Sum of matrices 'a' and 'b':")
print(sum_matrix)
Sum of matrices 'a' and 'b':
[[ 2 4 33 44 55]
 [ 55 44 33 4 2]
 [ 66 77 88 99 110]
 [110 99 88 77 66]
 [121 132 143 154 165]]

#8 Subtracting matrix 'b' from 'a'


In [ ]:
diff_matrix = a - b
print("Subtraction of matrix 'b' from 'a':")
print(diff_matrix)
Subtraction of matrix 'b' from 'a':
[[ 0 0 -27 -36 -45]
 [ -45 -36 -27 0 0]
 [ -54 -63 -72 -81 -90]
 [ -90 -81 -72 -63 -54]
 [ -99 -108 -117 -126 -135]]

#9 Multiplying matrix a by b element wise and matrix multiplication

In [ ]:
#Element-wise multiplication
elementwise_product = a * b
print("Element-wise multiplication of matrices 'a' and 'b':")
print(elementwise_product)
# Matrix multiplication (Dot product)
matrix_product = np.dot(a, b)
print("Matrix multiplication of matrices 'a' and 'b':")
print(matrix_product)
Element-wise multiplication of matrices 'a' and 'b':
[[ 1 4 90 160 250]
 [ 250 160 90 4 1]
 [ 360 490 640 810 1000]
 [1000 810 640 490 360]
 [1210 1440 1690 1960 2250]]
Matrix multiplication of matrices 'a' and 'b':
[[1231 1252 1300 1294 1342]
 [ 695 680 800 758 824]
 [2836 2862 3050 3004 3147]
 [2300 2290 2550 2468 2629]
 [4441 4472 4800 4714 4952]]

#10 Dividing each element of matrix a and b by 18

In [ ]:
a_divided = a / 18
b_divided = b / 18
print("Matrix 'a' after element-wise division:")
print(a_divided)
print("Matrix 'b' after element-wise division:")
print(b_divided)
Matrix 'a' after element-wise division:
[[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.27777778 0.22222222 0.16666667 0.11111111 0.05555556]
  [0.33333333 0.38888889 0.44444444 0.5 0.55555556]
 [0.55555556 0.5 0.44444444 0.38888889 0.33333333]
 [0.61111111 0.66666667 0.72222222 0.77777778 0.83333333]]
Matrix 'b' after element-wise division:
[[0.05555556 0.11111111 1.66666667 2.22222222 2.77777778]
 [2.77777778 2.22222222 1.66666667 0.11111111 0.05555556]
 [3.33333333 3.88888889 4.44444444 5. 5.55555556]
 [5.55555556 5. 4.44444444 3.88888889 3.33333333]
 [6.11111111 6.66666667 7.22222222 7.77777778 8.33333333]]


#11 Finding the inverse, rank, condition number, singular value decomposition and the norm of matrices a and b


In [ ]:
#Inverses of matrices
a_det = np.linalg.det(a)
b_det = np.linalg.det(b)
print("Determinant of a is:")
print(a_det)
print("Inverse of matrix 'a' does not exist since determinant of a is 0")
print("Determinant of b is:")
print(b_det)
print("Inverse of matrix 'b' does not exist since determinant of b is 0")
# Rank of matrices
rank_a = np.linalg.matrix_rank(a)
rank_b = np.linalg.matrix_rank(b)
print("Rank of matrix 'a':", rank_a)
print("Rank of matrix 'b':", rank_b)
# Condition number of matrices
cond_a = np.linalg.cond(a)
cond_b = np.linalg.cond(b)
print("Condition number of matrix 'a':", cond_a)
print("Condition number of matrix 'b':", cond_b)
# Singular Value Decomposition (SVD)
u_a, s_a, vh_a = np.linalg.svd(a)
u_b, s_b, vh_b = np.linalg.svd(b)
print("Singular Value Decomposition of matrix 'a':")
print("U:")
print(u_a)
print("Singular values:")
print(s_a)
print("V^H:")
print(vh_a)
print("Singular Value Decomposition of matrix 'b':")
print("U:")
print(u_b)
print("Singular values:")
print(s_b)
print("V^H:")
print(vh_b)
# Norms of matrices
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
print("Norm of matrix 'a':", norm_a)
print("Norm of matrix 'b':", norm_b)
Determinant of a is:
0.0
Inverse of matrix 'a' does not exist since determinant of a is 0
Determinant of b is:
0.0
Inverse of matrix 'b' does not exist since determinant of b is 0
Rank of matrix 'a': 2
Rank of matrix 'b': 4
Condition number of matrix 'a': 9.944187924572022e+16
Condition number of matrix 'b': 2.1710698299149046e+18
Singular Value Decomposition of matrix 'a':
U:
[[-0.17320063 0.41300185 0.87976009 -0.15325862 -0.0443282 ]
 [-0.16366307 -0.53360701 0.2298415 -0.15957037 0.7811454 ]
 [-0.45392038 0.31249755 -0.08616664 0.77322155 0.30167085]
 [-0.44438283 -0.63411131 0.22330018 0.2326975 -0.54444067]
 [-0.73464014 0.21199325 -0.34045178 -0.5468358 -0.02063792]]
Singular values:
[3.97557668e+01 6.66925814e+00 2.24034336e-15 6.76022299e-16
 3.99788973e-16]
V^H:
[[-0.40849188 -0.42745052 -0.44640916 -0.4653678 -0.48432644]
 [-0.65812946 -0.34247051 -0.02681156 0.28884738 0.60450633]
 [ 0.42007059 -0.59079297 -0.25980347 0.61170351 -0.18117765]
 [-0.16985507 0.57996879 -0.70928684 0.35808758 -0.05891446]
 [-0.44123685 0.12082992 0.47897216 0.44451333 -0.60307856]]
Singular Value Decomposition of matrix 'b':
U:
[[-1.46251152e-01 5.09759111e-01 7.58698419e-01 -3.78329167e-01
 -4.00615287e-16]
 [-1.32738939e-01 -5.96948879e-01 6.20376803e-01 4.91085565e-01
 -3.97819952e-16]
 [-4.58273859e-01 2.58151879e-01 -1.02505513e-01 3.19424440e-01
 -7.81539074e-01]
 [-4.48347747e-01 -5.36525388e-01 -6.84613549e-02 -6.86885588e-01
 -1.86080732e-01]
 [-7.41593111e-01 1.71160158e-01 -1.55932659e-01 2.04592831e-01
 5.95458342e-01]]
Singular values:
[3.93859553e+02 7.88592217e+01 1.04515921e+01 7.52597152e+00
 1.81412660e-16]
V^H:
[[-0.40798718 -0.42406919 -0.45017706 -0.46353465 -0.4859918 ]
 [-0.61722006 -0.41258169 -0.03341084 0.36566149 0.56034912]
 [ 0.15581165 -0.54693657 0.71029002 -0.40756211 0.07722903]
 [-0.37761661 0.52855793 0.07744757 -0.64334428 0.39767101]
 [ 0.53452248 -0.26726124 -0.53452248 -0.26726124 0.53452248]]
Norm of matrix 'a': 40.311288741492746
Norm of matrix 'b': 401.88306757065544


#12 Finding the norm, inner product and outer product of column vector

In [ ]:
#Finding the norm of column vector
import numpy as np
# Defining column vector as a numpy array
col_vect = np.array([[1],
[2],
[3]])
norm = np.linalg.norm(col_vect)
print("The norm of the column vector is:", norm)
# Finding inner product and outer product
col_vect_a=np.array([[1], # intializing two columne vectors a and b
[2],
[3]])
col_vect_b=np.array([[4],
[5],
[6]])
inner_prod=np.dot(col_vect_a.T,col_vect_b)
outer_prod=np.dot(col_vect_a,col_vect_b.T)
print("Inner product of column vector a and b:", inner_prod)
print("Outer product of column vector a and b:", outer_prod)
The norm of the column vector is: 3.7416573867739413
Inner product of column vector a and b: [[32]]
Outer product of column vector a and b: [[ 4 5 6]
 [ 8 10 12]
 [12 15 18]]


#13 Writing a function called derivative which takes input parameters f(x), a, method (forward,backward and central) and h(step size)

In [ ]:
import numpy as np
def derivative(f, a, method='central', h=0.01):
if method == 'forward':
return (f(a + h) - f(a)) / h
elif method == 'backward':
return (f(a) - f(a - h)) / h
elif method == 'central':
return (f(a + h) - f(a - h)) / (2 * h)
else:
raise ValueError("Invalid method. Choose 'forward', 'backward', or 'central'.")
# Test the derivative function
x = 0.5
# Function: f(x) = exp(x)
exp_derivative_forward = derivative(np.exp, x, method='forward') # for x =0.5 forward derivative is carried out in ex()
exp_derivative_backward = derivative(np.exp, x, method='backward') #for x =0.5 backward derivative is carried out in ex()
exp_derivative_central = derivative(np.exp, x, method='central') #for x =0.5 central derivative is carried out in ex()
print("Derivative of exp(x) at x =", x)
print("Forward difference:", exp_derivative_forward)
print("Backward difference:", exp_derivative_backward)
print("Central difference:", exp_derivative_central)
# Function: f(x) = cos(x)
cos_derivative_forward = derivative(np.cos, x, method='forward') #for x =0.5 forward derivative is carried out in cos()
cos_derivative_backward = derivative(np.cos, x, method='backward') #for x =0.5 backward derivative is carried out in cos()
cos_derivative_central = derivative(np.cos, x, method='central') #for x =0.5 backward derivative is carried out in cos()
print("\nDerivative of cos(x) at x =", x)
print("Forward difference:", cos_derivative_forward)
print("Backward difference:", cos_derivative_backward)
print("Central difference:", cos_derivative_central)
Derivative of exp(x) at x = 0.5
Forward difference: 1.6569924245758205
Backward difference: 1.6405050744749294
Central difference: 1.648748749525375
Derivative of cos(x) at x = 0.5
Forward difference: -0.483805424462147
Backward difference: -0.4750296719748692
Central difference: -0.4794175482185081

#14 Downloading the Automatic Weather Station AWS Data. Reading the .csv file using pandas library as a DataFrame.


In [ ]:
import pandas as pd
# Providing the path to my uploaded imd_maitri.csv file
csv_file_path = "/content/bang_csv.csv"
# Reading the CSV file into a DataFrame
df = pd.read_csv(csv_file_path)
print(df)
 _id SL NO District Taluk Hobli \
0 1 1 Bangalore Urban Bangalore East Bidarahalli
1 2 2 Bangalore Urban Bangalore East Krishnarajapura
2 3 3 Bangalore Urban Bangalore East Krishnarajapura
3 4 4 Bangalore Urban Bangalore East Krishnarajapura
4 5 5 Bangalore Urban Bangalore East Krishnarajapura
.. ... ... ... ... ...
192 193 193 Bangalore Rural Hosakote Nandagudi
193 194 194 Bangalore Rural Hosakote Sulibele
194 195 195 Bangalore Rural Nelamangala Nelamangala
195 196 196 Bangalore Rural Nelamangala Sompura
196 197 197 Bangalore Rural Nelamangala Thyamagondlu
 Hobli/GP/Location Date of Commission
0 Kadugodi 2013-07-26T00:00:00
1 Banaswadi 2013-06-24T00:00:00
2 Basavanapura 2013-07-16T00:00:00
3 Benniganahalli 2013-07-16T00:00:00
4 Dommalur 2013-06-24T00:00:00
.. ... ...
192 Nandagudi 2014-02-01T00:00:00
193 Sulibele 2013-12-31T00:00:00
194 Nelamangala 2009-06-05T00:00:00
195 Sompura 2013-12-24T00:00:00
196 Thyamagondlu 2013-12-24T00:00:00
[197 rows x 7 columns]